"""
    Misc utils
"""
import os
import torch as ch


# Read environment variables
CACHE_PATH = os.environ.get("MIB_CACHE_SOURCE", None)
DATA_SOURCE = os.environ.get("MIB_DATA_SOURCE", None)


def get_models_path():
    """
    Get path to models.
    Returns:
        str: path to models
    """
    return os.path.join(get_cache_path(), "models")


def get_signals_path():
    """
    Get path to signals (generated by attacks).
    Returns:
        str: path to attack signa;s
    """
    return os.path.join(get_cache_path(), "signals")


def get_cache_path():
    """
    Get path to cache directory.
    Returns:
        str: path to cache directory
    """
    if CACHE_PATH is None:
        raise ValueError("MIB_CACHE_SOURCE= environment variable not set")
    return CACHE_PATH


def get_data_source():
    """
    Get path to data source directory.
    Returns:
        str: path to data source directory
    """
    if DATA_SOURCE is None:
        raise ValueError("MIB_DATA_SOURCE environment variable not set")
    return DATA_SOURCE

